// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Module } from "./Module";

export interface AllModules { data: Array<Module>, }