// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Row } from "./Row";

export interface Module { name: string, rows: Array<Row>, }