// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowElement } from "./RowElement";

export interface Row { input: string | null, output: string | null, elements: Array<RowElement>, }