// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Selector } from "./Selector";
import type { Slider } from "./Slider";
import type { Text } from "./Text";

export type RowElement = { type: "TEXT" } & Text | { type: "SLIDER" } & Slider | { type: "SELECTOR" } & Selector;