// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Slider { steps: number, order: number, range: number, inverts: boolean, default: number, parameter: string, }