// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Justify } from "./Justify";

export interface Text { data: string, justify: Justify, }