import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { ToggleButton } from "../components/ToggleButton";
import { Oscilloscope } from "../components/Oscilloscope";
import { ModuleArea } from "../components/Modules";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Modular Synth App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModuleArea />
      <ToggleButton />
      <Oscilloscope />
    </div>
  );
};

export default Home;
