import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import TestOsc from "../components/TestOsc";

const Home: NextPage = () => {
  useEffect(() => {
    // Wasm test :)
    // greet();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Modular Synth App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestOsc />
    </div>
  );
};

export default Home;
