[package]
name = "audio_graph"
description = "A digital audio signal processing graph. Forked from dasp_graph"
version = "0.1.0"
authors = ["Oliver Frank <oliverfrank321@gmail.com>", "mitchmindtree <mitchell.nordine@gmail.com>"]
readme = "../README.md"
keywords = ["dsp", "audio", "graph", "pcm", "audio"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
dasp_frame = { version = "0.11", default-features = false, features = ["std"] }
dasp_ring_buffer = { version = "0.11", default-features = false, features = ["std"] }
dasp_signal = { version = "0.11", default-features = false, features = ["std"] }
dasp_slice = { version = "0.11", default-features = false, features = ["std"] }
petgraph = { version = "0.5", default-features = false }

[dev-dependencies]
petgraph = { version = "0.5", features = ["stable_graph"] }
